export const ZH = {
  attachedImage: (name?: string) => (name ? `📎 已附加图片: ${name}` : '📎 已附加图片'),
  backgroundTasks: (count: number) => `${count} 个后台任务运行中`,
  copiedChars: (count: number) => `已复制 ${count} 个字符`,
  detectedFile: (name: string) => `已检测到文件: ${name}`,
  emptySystemMessage: '（系统消息）',
  emptyToolResult: '（工具结果为空）',
  error: (message: string) => `错误: ${message}`,
  failedToOpenEditor: (message?: string) => (message ? `打开编辑器失败: ${message}` : '打开编辑器失败'),
  exitCode: (code: number | string) => `退出码 ${code}`,
  invalidResponse: (method: string) => `错误: ${method} 响应无效`,
  interruptCurrentTurnFirst: '请先中断当前轮次，再继续操作',
  interrupted: '已中断',
  interruptedMarkdown: '*[已中断]*',
  loadingSkill: (name: string) => `⚡ 正在加载技能: ${name}`,
  longMessageLabel: '[长消息]',
  noClipboardImage: '剪贴板里没有图片',
  noOutput: '（无输出）',
  promptCancelled: '提示已取消',
  queued: (text: string) => `已加入队列: "${text.slice(0, 50)}${text.length > 50 ? '…' : ''}"`,
  queuedWhileSessionInitializes: '（会话初始化中，已排队）',
  sessionNotReady: '会话尚未就绪',
  sessionTitleSet: (title: string, suffix = '') => `会话标题已设置: ${title}${suffix}`,
  setSessionTitleFailed: (message: string) => `警告: 会话标题设置失败: ${message}`,
  skillPayloadMissing: (name: string) => `/${name}: 技能载荷缺少消息`,
  steerFailedQueued: '插入当前轮次失败，已加入下一轮队列',
  sudoCancelled: 'sudo 已取消',
  emptyMessage: (name: string) => `/${name}: 消息为空`,
  voiceError: (message: string) => `语音错误: ${message}`,
  voiceModeOff: '语音模式未开启，请先使用 /voice on',
  voiceStillTranscribing: '语音仍在转写，请稍后再试',
  warning: (message: string) => `警告: ${message}`
} as const
